# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.statistic_map import StatisticMap


class TestStatisticMap(unittest.TestCase):
    """ StatisticMap unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatisticMap(self):
        """
        Test StatisticMap
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.statistic_map.StatisticMap()
        pass


if __name__ == '__main__':
    unittest.main()
