# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.rep_target import RepTarget


class TestRepTarget(unittest.TestCase):
    """ RepTarget unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepTarget(self):
        """
        Test RepTarget
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.rep_target.RepTarget()
        pass


if __name__ == '__main__':
    unittest.main()
