# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ConfigurationsScanAllPolicy(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'parameter': 'ConfigurationsScanAllPolicyParameter'
    }

    attribute_map = {
        'type': 'type',
        'parameter': 'parameter'
    }

    def __init__(self, type=None, parameter=None):
        """
        ConfigurationsScanAllPolicy - a model defined in Swagger
        """

        self._type = None
        self._parameter = None

        if type is not None:
          self.type = type
        if parameter is not None:
          self.parameter = parameter

    @property
    def type(self):
        """
        Gets the type of this ConfigurationsScanAllPolicy.
        The type of scan all policy, currently the valid values are \"none\" and \"daily\"

        :return: The type of this ConfigurationsScanAllPolicy.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ConfigurationsScanAllPolicy.
        The type of scan all policy, currently the valid values are \"none\" and \"daily\"

        :param type: The type of this ConfigurationsScanAllPolicy.
        :type: str
        """

        self._type = type

    @property
    def parameter(self):
        """
        Gets the parameter of this ConfigurationsScanAllPolicy.

        :return: The parameter of this ConfigurationsScanAllPolicy.
        :rtype: ConfigurationsScanAllPolicyParameter
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """
        Sets the parameter of this ConfigurationsScanAllPolicy.

        :param parameter: The parameter of this ConfigurationsScanAllPolicy.
        :type: ConfigurationsScanAllPolicyParameter
        """

        self._parameter = parameter

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ConfigurationsScanAllPolicy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
