# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class HasAdminRole(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'has_admin_role': 'int'
    }

    attribute_map = {
        'has_admin_role': 'has_admin_role'
    }

    def __init__(self, has_admin_role=None):
        """
        HasAdminRole - a model defined in Swagger
        """

        self._has_admin_role = None

        if has_admin_role is not None:
          self.has_admin_role = has_admin_role

    @property
    def has_admin_role(self):
        """
        Gets the has_admin_role of this HasAdminRole.
        1-has admin, 0-not.

        :return: The has_admin_role of this HasAdminRole.
        :rtype: int
        """
        return self._has_admin_role

    @has_admin_role.setter
    def has_admin_role(self, has_admin_role):
        """
        Sets the has_admin_role of this HasAdminRole.
        1-has admin, 0-not.

        :param has_admin_role: The has_admin_role of this HasAdminRole.
        :type: int
        """

        self._has_admin_role = has_admin_role

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, HasAdminRole):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
