# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ProjectReq(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_name': 'str',
        'public': 'int',
        'enable_content_trust': 'bool',
        'prevent_vulnerable_images_from_running': 'bool',
        'prevent_vulnerable_images_from_running_severity': 'str',
        'automatically_scan_images_on_push': 'bool'
    }

    attribute_map = {
        'project_name': 'project_name',
        'public': 'public',
        'enable_content_trust': 'enable_content_trust',
        'prevent_vulnerable_images_from_running': 'prevent_vulnerable_images_from_running',
        'prevent_vulnerable_images_from_running_severity': 'prevent_vulnerable_images_from_running_severity',
        'automatically_scan_images_on_push': 'automatically_scan_images_on_push'
    }

    def __init__(self, project_name=None, public=None, enable_content_trust=None, prevent_vulnerable_images_from_running=None, prevent_vulnerable_images_from_running_severity=None, automatically_scan_images_on_push=None):
        """
        ProjectReq - a model defined in Swagger
        """

        self._project_name = None
        self._public = None
        self._enable_content_trust = None
        self._prevent_vulnerable_images_from_running = None
        self._prevent_vulnerable_images_from_running_severity = None
        self._automatically_scan_images_on_push = None

        if project_name is not None:
          self.project_name = project_name
        if public is not None:
          self.public = public
        if enable_content_trust is not None:
          self.enable_content_trust = enable_content_trust
        if prevent_vulnerable_images_from_running is not None:
          self.prevent_vulnerable_images_from_running = prevent_vulnerable_images_from_running
        if prevent_vulnerable_images_from_running_severity is not None:
          self.prevent_vulnerable_images_from_running_severity = prevent_vulnerable_images_from_running_severity
        if automatically_scan_images_on_push is not None:
          self.automatically_scan_images_on_push = automatically_scan_images_on_push

    @property
    def project_name(self):
        """
        Gets the project_name of this ProjectReq.
        The name of the project.

        :return: The project_name of this ProjectReq.
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """
        Sets the project_name of this ProjectReq.
        The name of the project.

        :param project_name: The project_name of this ProjectReq.
        :type: str
        """

        self._project_name = project_name

    @property
    def public(self):
        """
        Gets the public of this ProjectReq.
        The public status of the project.

        :return: The public of this ProjectReq.
        :rtype: int
        """
        return self._public

    @public.setter
    def public(self, public):
        """
        Sets the public of this ProjectReq.
        The public status of the project.

        :param public: The public of this ProjectReq.
        :type: int
        """

        self._public = public

    @property
    def enable_content_trust(self):
        """
        Gets the enable_content_trust of this ProjectReq.
        Whether content trust is enabled or not. If it is enabled, user cann't pull unsigned images from this project.

        :return: The enable_content_trust of this ProjectReq.
        :rtype: bool
        """
        return self._enable_content_trust

    @enable_content_trust.setter
    def enable_content_trust(self, enable_content_trust):
        """
        Sets the enable_content_trust of this ProjectReq.
        Whether content trust is enabled or not. If it is enabled, user cann't pull unsigned images from this project.

        :param enable_content_trust: The enable_content_trust of this ProjectReq.
        :type: bool
        """

        self._enable_content_trust = enable_content_trust

    @property
    def prevent_vulnerable_images_from_running(self):
        """
        Gets the prevent_vulnerable_images_from_running of this ProjectReq.
        Whether prevent the vulnerable images from running.

        :return: The prevent_vulnerable_images_from_running of this ProjectReq.
        :rtype: bool
        """
        return self._prevent_vulnerable_images_from_running

    @prevent_vulnerable_images_from_running.setter
    def prevent_vulnerable_images_from_running(self, prevent_vulnerable_images_from_running):
        """
        Sets the prevent_vulnerable_images_from_running of this ProjectReq.
        Whether prevent the vulnerable images from running.

        :param prevent_vulnerable_images_from_running: The prevent_vulnerable_images_from_running of this ProjectReq.
        :type: bool
        """

        self._prevent_vulnerable_images_from_running = prevent_vulnerable_images_from_running

    @property
    def prevent_vulnerable_images_from_running_severity(self):
        """
        Gets the prevent_vulnerable_images_from_running_severity of this ProjectReq.
        If the vulnerability is high than severity defined here, the images cann't be pulled.

        :return: The prevent_vulnerable_images_from_running_severity of this ProjectReq.
        :rtype: str
        """
        return self._prevent_vulnerable_images_from_running_severity

    @prevent_vulnerable_images_from_running_severity.setter
    def prevent_vulnerable_images_from_running_severity(self, prevent_vulnerable_images_from_running_severity):
        """
        Sets the prevent_vulnerable_images_from_running_severity of this ProjectReq.
        If the vulnerability is high than severity defined here, the images cann't be pulled.

        :param prevent_vulnerable_images_from_running_severity: The prevent_vulnerable_images_from_running_severity of this ProjectReq.
        :type: str
        """

        self._prevent_vulnerable_images_from_running_severity = prevent_vulnerable_images_from_running_severity

    @property
    def automatically_scan_images_on_push(self):
        """
        Gets the automatically_scan_images_on_push of this ProjectReq.
        Whether scan images automatically when pushing.

        :return: The automatically_scan_images_on_push of this ProjectReq.
        :rtype: bool
        """
        return self._automatically_scan_images_on_push

    @automatically_scan_images_on_push.setter
    def automatically_scan_images_on_push(self, automatically_scan_images_on_push):
        """
        Sets the automatically_scan_images_on_push of this ProjectReq.
        Whether scan images automatically when pushing.

        :param automatically_scan_images_on_push: The automatically_scan_images_on_push of this ProjectReq.
        :type: bool
        """

        self._automatically_scan_images_on_push = automatically_scan_images_on_push

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ProjectReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
