# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RepPolicyPost(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'int',
        'target_id': 'int',
        'name': 'str',
        'enabled': 'int'
    }

    attribute_map = {
        'project_id': 'project_id',
        'target_id': 'target_id',
        'name': 'name',
        'enabled': 'enabled'
    }

    def __init__(self, project_id=None, target_id=None, name=None, enabled=None):
        """
        RepPolicyPost - a model defined in Swagger
        """

        self._project_id = None
        self._target_id = None
        self._name = None
        self._enabled = None

        if project_id is not None:
          self.project_id = project_id
        if target_id is not None:
          self.target_id = target_id
        if name is not None:
          self.name = name
        if enabled is not None:
          self.enabled = enabled

    @property
    def project_id(self):
        """
        Gets the project_id of this RepPolicyPost.
        The project ID.

        :return: The project_id of this RepPolicyPost.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """
        Sets the project_id of this RepPolicyPost.
        The project ID.

        :param project_id: The project_id of this RepPolicyPost.
        :type: int
        """

        self._project_id = project_id

    @property
    def target_id(self):
        """
        Gets the target_id of this RepPolicyPost.
        The target ID.

        :return: The target_id of this RepPolicyPost.
        :rtype: int
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """
        Sets the target_id of this RepPolicyPost.
        The target ID.

        :param target_id: The target_id of this RepPolicyPost.
        :type: int
        """

        self._target_id = target_id

    @property
    def name(self):
        """
        Gets the name of this RepPolicyPost.
        The policy name.

        :return: The name of this RepPolicyPost.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this RepPolicyPost.
        The policy name.

        :param name: The name of this RepPolicyPost.
        :type: str
        """

        self._name = name

    @property
    def enabled(self):
        """
        Gets the enabled of this RepPolicyPost.
        1-enable, 0-disable

        :return: The enabled of this RepPolicyPost.
        :rtype: int
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """
        Sets the enabled of this RepPolicyPost.
        1-enable, 0-disable

        :param enabled: The enabled of this RepPolicyPost.
        :type: int
        """

        self._enabled = enabled

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RepPolicyPost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
