# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RepTarget(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'endpoint': 'str',
        'name': 'str',
        'username': 'str',
        'password': 'str',
        'type': 'int',
        'creation_time': 'str',
        'update_time': 'str'
    }

    attribute_map = {
        'id': 'id',
        'endpoint': 'endpoint',
        'name': 'name',
        'username': 'username',
        'password': 'password',
        'type': 'type',
        'creation_time': 'creation_time',
        'update_time': 'update_time'
    }

    def __init__(self, id=None, endpoint=None, name=None, username=None, password=None, type=None, creation_time=None, update_time=None):
        """
        RepTarget - a model defined in Swagger
        """

        self._id = None
        self._endpoint = None
        self._name = None
        self._username = None
        self._password = None
        self._type = None
        self._creation_time = None
        self._update_time = None

        if id is not None:
          self.id = id
        if endpoint is not None:
          self.endpoint = endpoint
        if name is not None:
          self.name = name
        if username is not None:
          self.username = username
        if password is not None:
          self.password = password
        if type is not None:
          self.type = type
        if creation_time is not None:
          self.creation_time = creation_time
        if update_time is not None:
          self.update_time = update_time

    @property
    def id(self):
        """
        Gets the id of this RepTarget.
        The target ID.

        :return: The id of this RepTarget.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this RepTarget.
        The target ID.

        :param id: The id of this RepTarget.
        :type: int
        """

        self._id = id

    @property
    def endpoint(self):
        """
        Gets the endpoint of this RepTarget.
        The target address URL string.

        :return: The endpoint of this RepTarget.
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """
        Sets the endpoint of this RepTarget.
        The target address URL string.

        :param endpoint: The endpoint of this RepTarget.
        :type: str
        """

        self._endpoint = endpoint

    @property
    def name(self):
        """
        Gets the name of this RepTarget.
        The target name.

        :return: The name of this RepTarget.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this RepTarget.
        The target name.

        :param name: The name of this RepTarget.
        :type: str
        """

        self._name = name

    @property
    def username(self):
        """
        Gets the username of this RepTarget.
        The target server username.

        :return: The username of this RepTarget.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this RepTarget.
        The target server username.

        :param username: The username of this RepTarget.
        :type: str
        """

        self._username = username

    @property
    def password(self):
        """
        Gets the password of this RepTarget.
        The target server password.

        :return: The password of this RepTarget.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this RepTarget.
        The target server password.

        :param password: The password of this RepTarget.
        :type: str
        """

        self._password = password

    @property
    def type(self):
        """
        Gets the type of this RepTarget.
        Reserved field.

        :return: The type of this RepTarget.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this RepTarget.
        Reserved field.

        :param type: The type of this RepTarget.
        :type: int
        """

        self._type = type

    @property
    def creation_time(self):
        """
        Gets the creation_time of this RepTarget.
        The create time of the policy.

        :return: The creation_time of this RepTarget.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """
        Sets the creation_time of this RepTarget.
        The create time of the policy.

        :param creation_time: The creation_time of this RepTarget.
        :type: str
        """

        self._creation_time = creation_time

    @property
    def update_time(self):
        """
        Gets the update_time of this RepTarget.
        The update time of the policy.

        :return: The update_time of this RepTarget.
        :rtype: str
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """
        Sets the update_time of this RepTarget.
        The update time of the policy.

        :param update_time: The update_time of this RepTarget.
        :type: str
        """

        self._update_time = update_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RepTarget):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
