# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RepPolicy(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'project_id': 'int',
        'project_name': 'str',
        'target_id': 'int',
        'name': 'str',
        'enabled': 'int',
        'description': 'str',
        'cron_str': 'str',
        'start_time': 'str',
        'creation_time': 'str',
        'update_time': 'str',
        'deleted': 'int'
    }

    attribute_map = {
        'id': 'id',
        'project_id': 'project_id',
        'project_name': 'project_name',
        'target_id': 'target_id',
        'name': 'name',
        'enabled': 'enabled',
        'description': 'description',
        'cron_str': 'cron_str',
        'start_time': 'start_time',
        'creation_time': 'creation_time',
        'update_time': 'update_time',
        'deleted': 'deleted'
    }

    def __init__(self, id=None, project_id=None, project_name=None, target_id=None, name=None, enabled=None, description=None, cron_str=None, start_time=None, creation_time=None, update_time=None, deleted=None):
        """
        RepPolicy - a model defined in Swagger
        """

        self._id = None
        self._project_id = None
        self._project_name = None
        self._target_id = None
        self._name = None
        self._enabled = None
        self._description = None
        self._cron_str = None
        self._start_time = None
        self._creation_time = None
        self._update_time = None
        self._deleted = None

        if id is not None:
          self.id = id
        if project_id is not None:
          self.project_id = project_id
        if project_name is not None:
          self.project_name = project_name
        if target_id is not None:
          self.target_id = target_id
        if name is not None:
          self.name = name
        if enabled is not None:
          self.enabled = enabled
        if description is not None:
          self.description = description
        if cron_str is not None:
          self.cron_str = cron_str
        if start_time is not None:
          self.start_time = start_time
        if creation_time is not None:
          self.creation_time = creation_time
        if update_time is not None:
          self.update_time = update_time
        if deleted is not None:
          self.deleted = deleted

    @property
    def id(self):
        """
        Gets the id of this RepPolicy.
        The policy ID.

        :return: The id of this RepPolicy.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this RepPolicy.
        The policy ID.

        :param id: The id of this RepPolicy.
        :type: int
        """

        self._id = id

    @property
    def project_id(self):
        """
        Gets the project_id of this RepPolicy.
        The project ID.

        :return: The project_id of this RepPolicy.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """
        Sets the project_id of this RepPolicy.
        The project ID.

        :param project_id: The project_id of this RepPolicy.
        :type: int
        """

        self._project_id = project_id

    @property
    def project_name(self):
        """
        Gets the project_name of this RepPolicy.
        The project name.

        :return: The project_name of this RepPolicy.
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """
        Sets the project_name of this RepPolicy.
        The project name.

        :param project_name: The project_name of this RepPolicy.
        :type: str
        """

        self._project_name = project_name

    @property
    def target_id(self):
        """
        Gets the target_id of this RepPolicy.
        The target ID.

        :return: The target_id of this RepPolicy.
        :rtype: int
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """
        Sets the target_id of this RepPolicy.
        The target ID.

        :param target_id: The target_id of this RepPolicy.
        :type: int
        """

        self._target_id = target_id

    @property
    def name(self):
        """
        Gets the name of this RepPolicy.
        The policy name.

        :return: The name of this RepPolicy.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this RepPolicy.
        The policy name.

        :param name: The name of this RepPolicy.
        :type: str
        """

        self._name = name

    @property
    def enabled(self):
        """
        Gets the enabled of this RepPolicy.
        The policy's enabled status.

        :return: The enabled of this RepPolicy.
        :rtype: int
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """
        Sets the enabled of this RepPolicy.
        The policy's enabled status.

        :param enabled: The enabled of this RepPolicy.
        :type: int
        """

        self._enabled = enabled

    @property
    def description(self):
        """
        Gets the description of this RepPolicy.
        The description of the policy.

        :return: The description of this RepPolicy.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this RepPolicy.
        The description of the policy.

        :param description: The description of this RepPolicy.
        :type: str
        """

        self._description = description

    @property
    def cron_str(self):
        """
        Gets the cron_str of this RepPolicy.
        The cron string for schedule job.

        :return: The cron_str of this RepPolicy.
        :rtype: str
        """
        return self._cron_str

    @cron_str.setter
    def cron_str(self, cron_str):
        """
        Sets the cron_str of this RepPolicy.
        The cron string for schedule job.

        :param cron_str: The cron_str of this RepPolicy.
        :type: str
        """

        self._cron_str = cron_str

    @property
    def start_time(self):
        """
        Gets the start_time of this RepPolicy.
        The start time of the policy.

        :return: The start_time of this RepPolicy.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """
        Sets the start_time of this RepPolicy.
        The start time of the policy.

        :param start_time: The start_time of this RepPolicy.
        :type: str
        """

        self._start_time = start_time

    @property
    def creation_time(self):
        """
        Gets the creation_time of this RepPolicy.
        The create time of the policy.

        :return: The creation_time of this RepPolicy.
        :rtype: str
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """
        Sets the creation_time of this RepPolicy.
        The create time of the policy.

        :param creation_time: The creation_time of this RepPolicy.
        :type: str
        """

        self._creation_time = creation_time

    @property
    def update_time(self):
        """
        Gets the update_time of this RepPolicy.
        The update time of the policy.

        :return: The update_time of this RepPolicy.
        :rtype: str
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """
        Sets the update_time of this RepPolicy.
        The update time of the policy.

        :param update_time: The update_time of this RepPolicy.
        :type: str
        """

        self._update_time = update_time

    @property
    def deleted(self):
        """
        Gets the deleted of this RepPolicy.

        :return: The deleted of this RepPolicy.
        :rtype: int
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """
        Sets the deleted of this RepPolicy.

        :param deleted: The deleted of this RepPolicy.
        :type: int
        """

        self._deleted = deleted

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RepPolicy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
