# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RepoSignature(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'str',
        'hashes': 'object'
    }

    attribute_map = {
        'tag': 'tag',
        'hashes': 'hashes'
    }

    def __init__(self, tag=None, hashes=None):
        """
        RepoSignature - a model defined in Swagger
        """

        self._tag = None
        self._hashes = None

        if tag is not None:
          self.tag = tag
        if hashes is not None:
          self.hashes = hashes

    @property
    def tag(self):
        """
        Gets the tag of this RepoSignature.
        The tag of image.

        :return: The tag of this RepoSignature.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """
        Sets the tag of this RepoSignature.
        The tag of image.

        :param tag: The tag of this RepoSignature.
        :type: str
        """

        self._tag = tag

    @property
    def hashes(self):
        """
        Gets the hashes of this RepoSignature.
        The JSON object of the hash of the image.

        :return: The hashes of this RepoSignature.
        :rtype: object
        """
        return self._hashes

    @hashes.setter
    def hashes(self, hashes):
        """
        Sets the hashes of this RepoSignature.
        The JSON object of the hash of the image.

        :param hashes: The hashes of this RepoSignature.
        :type: object
        """

        self._hashes = hashes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RepoSignature):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
