# coding: utf-8

"""
    Harbor API

    These APIs provide services for manipulating Harbor project.

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RoleParam(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'roles': 'list[int]',
        'username': 'str'
    }

    attribute_map = {
        'roles': 'roles',
        'username': 'username'
    }

    def __init__(self, roles=None, username=None):
        """
        RoleParam - a model defined in Swagger
        """

        self._roles = None
        self._username = None

        if roles is not None:
          self.roles = roles
        if username is not None:
          self.username = username

    @property
    def roles(self):
        """
        Gets the roles of this RoleParam.
        Role ID for updating project role member.

        :return: The roles of this RoleParam.
        :rtype: list[int]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """
        Sets the roles of this RoleParam.
        Role ID for updating project role member.

        :param roles: The roles of this RoleParam.
        :type: list[int]
        """

        self._roles = roles

    @property
    def username(self):
        """
        Gets the username of this RoleParam.
        Username relevant to a project role member.

        :return: The username of this RoleParam.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this RoleParam.
        Username relevant to a project role member.

        :param username: The username of this RoleParam.
        :type: str
        """

        self._username = username

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RoleParam):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
